config/routes.rb
Rails.application.routes.draw do
  # post '/settings/create' => 'settings#create'

  get '/settings/edit' => 'settings#edit'

  # get '/settings/delete' => 'settings#delete'

  patch '/settings' => 'settings#update'

  root to: 'leads#index'

  devise_for :admins

  resources :leads
  get '/next' => 'leads#next'
  get '/no_leads' => 'leads#no_leads'
  get '/token' => 'leads#token'
  post '/voice' => 'leads#voice'
  post '/text' => 'leads#text'

  get '/daily_logs' => 'daily_progress_logs#index'

  post '/incoming_voice' => 'webhooks#incoming_voice'
  post '/incoming_text' => 'webhooks#incoming_text'

  namespace :api do
    namespace :v1 do
      get '/leads' => 'leads#index'
      get '/leads/:id' => 'leads#show'
      post '/leads' => 'leads#create'
    end
  end

end

app/models/lead.rb
# == Schema Information
#
# Table name: leads
#
#  id                        :integer          not null, primary key
#  first_name                :string
#  last_name                 :string
#  email                     :string
#  phone                     :string
#  ip                        :string
#  city                      :string
#  state                     :string
#  zip                       :string
#  contacted                 :boolean          default(FALSE)
#  appointment_date          :datetime
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  notes                     :text
#  connected                 :boolean          default(FALSE)
#  bad_number                :boolean          default(FALSE)
#  advisor                   :string
#  location                  :string
#  standard_phone            :string
#  exclude_from_calling      :boolean          default(FALSE)
#  process_time              :datetime
#  hot                       :boolean          default(TRUE)
#  first_appointment_set     :date
#  first_appointment_actual  :date
#  first_appointment_format  :string
#  second_appointment_set    :date
#  second_appointment_actual :date
#  second_appointment_format :string
#  enrolled_date             :date
#  deposit_date              :date
#  sales                     :integer
#  collected                 :integer
#  status                    :string
#  next_step                 :string
#  rep_notes                 :text
#  number_of_dials           :integer          default(0)
#  old_lead                  :boolean          default(FALSE)
#  meeting_type              :string
#  meeting_format            :string
#  ip_state                  :string
#  online                    :boolean          default(FALSE)
#

class Lead < ApplicationRecord
  has_many :events
  has_many :outreaches
  accepts_nested_attributes_for :outreaches
  before_save :standardize_phone

  attr_accessor :call_mode

  # The algorithm that decides which lead the call converter should call next
  # based on which lead is most likely to lead to a successful call. This algorithm
  # may change based on which call converter is calling.
  def self.next(admin_email=nil)
    return Lead.joins(:events).where(old_lead: false).where(exclude_from_calling: false).where(contacted: false).where(bad_number: false).where('enrolled_date is null').where("phone <> ''").where("events.name = 'Started Application'").order(:updated_at).last
  end

  # Send an automated text to a lead:
  def text
    @client = Twilio::REST::Client.new
    @client.messages.create(
    from: ENV['TWILIO_PHONE_NUMBER'],
      to: self.phone,
      body: 'Hi - this is Rena from Actualize. Do you have a minute to chat?'
    )
  end

  def full_name
    "#{self.try(:first_name).try(:capitalize)} #{self.try(:last_name).try(:capitalize)}"
  end

  def processed_within_minutes
    return 'not called' unless self.process_time
    number_of_seconds = self.process_time - self.created_at
    return "#{(number_of_seconds / 60).to_i} minutes"
  end

  # Reset a lead as if it's brand new. This is useful for manual testing.
  def reset
    self.update(hot: true, contacted: false, connected: false, exclude_from_calling: false, appointment_date: nil, advisor: nil, number_of_dials: 0, bad_number: false)
  end

  private

  def standardize_phone
    begin
      self.standard_phone = Phoner::Phone.parse(self.phone, country_code: '1').to_s
    rescue
      # We'll ignore an exception that could happen if the given phone 
      # number has a very unusual format
    end
  end

  def should_be_left_a_message
    # We tried dialing a valid number but the lead didn't answer their phone:
    self.contacted && !self.bad_number && !self.connected
  end
end

app/controllers/api/v1/leads_controller.rb
class Api::V1::LeadsController < ApplicationController

  def index
    @leads = Lead.all
    render "index.json.jbuilder"
  end

  def show
    @lead = Lead.find(params[:id])
    render "show.json.jbuilder"
  end

  def create
    # A lead is created by someone triggering an "event" on the website in 
    # which they submit information like a name and email address. 
    # If this is the first time this particular person triggered an event,
    # they become a lead, so we store both the lead and the particular
    # event they triggered. If they've triggered an event previously and already
    # become a lead in the past, we just record their new event.
    
    @lead = Lead.find_or_create_by(email: params[:email]) do |lead|
      lead.first_name = params[:first_name]
      lead.last_name = params[:last_name]
      lead.phone = params[:phone]
      lead.ip = params[:ip]
      lead.city = params[:city]
      lead.state = params[:state]
      lead.zip = params[:zip]
      lead.created_at = params[:created_at]
      lead.updated_at = params[:updated_at]
    end
    @lead.events.create(name: params[:name], created_at: params[:created_at], updated_at: params[:updated_at])
    render "show.json.jbuilder"
  end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :authenticate_admin!, except: [:token, :voice, :text]

  def index
    @all_leads_active = "active"
    @leads = Lead.where("phone <> ''").order(created_at: :desc)
    # If someone used the search box:
    @leads = Lead.where("first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ? OR phone ILIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").order(created_at: :desc) if params[:search]
  end

  # This is a special feature for call converters who can just call lead after
  # lead without thinking. That is, an automated algorithm decides who the 
  # call converter should call next based on which lead is most likely to answer
  # their phone at this time.
  def next
    @outbound_mode_active = "active"
    @lead = Lead.next(current_admin.email)
    @call_mode = true
    if @lead
      render :edit
    else
      redirect_to '/no_leads'
    end
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.create(lead_params)
    flash[:success] = "Lead added!"
    redirect_to '/'
  end

  def edit
    @lead = Lead.find_by(id: params[:id])
    @lead_outreaches = @lead.outreaches
    # We grab the entire text history from the Twilio API
    client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
    messages_from_lead = client.account.messages.list({
                  :to   => ENV['TWILIO_PHONE_NUMBER'], 
                  :from => @lead.phone
    })
    messages_from_call_converter = client.account.messages.list({
                  :to   => @lead.phone,
                  :from => ENV['TWILIO_PHONE_NUMBER']
    })
    @messages = (messages_from_lead + messages_from_call_converter).sort_by {|m| m.date_sent}

  end

  def update
    @lead = Lead.find_by(id: params[:id])
    if @lead.update(lead_params)    
      flash[:success] = "Lead saved!"
      redirect_to '/'
    else
      flash[:error] = "ERROR: We could not update this lead."
      render :next
    end
  end

  # This action is called by Twilio when preparing to make outbound voice calls
  # through the browser
  def token
    identity = Faker::Internet.user_name.gsub(/[^0-9a-z_]/i, '')

    capability = Twilio::Util::Capability.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
    # The Twilio 
    capability.allow_client_outgoing ENV['TWILIO_TWIML_APP_SID']
    capability.allow_client_incoming identity
    token = capability.generate

    render json: {identity: identity, token: token}
  end

  # Make voice calls through the browser. This web request gets called by Twilio
  # based on your Twilio settings, which can be modified at 
  # https://www.twilio.com/console/voice/runtime/twiml-apps
  def voice
    from_number = params['FromNumber'].blank? ? ENV['TWILIO_CALLER_ID'] : params['FromNumber']
    twiml = Twilio::TwiML::Response.new do |r|
      if params['To'] and params['To'] != ''
        r.Dial callerId: from_number do |d|
          # wrap the phone number or client name in the appropriate TwiML verb
          # by checking if the number given has only digits and format symbols
          if params['To'] =~ /^[\d\+\-\(\) ]+$/
            d.Number params['To']
          else
            d.Client params['To']
          end
        end
      else
        r.Say "Thanks for calling!"
      end
    end

    render xml: twiml.text
  end

  # Text from the browser:
  def text
    
    @client = Twilio::REST::Client.new
    @client.messages.create(
      from: ENV['TWILIO_PHONE_NUMBER'],
      to: params[:phone],
      body: params[:body]
    )

     redirect_to :back
  end

  def no_leads
  end

  private

  def lead_params
    params.require(:lead).permit(:first_name, :last_name, :email, :phone, :city, :state, :zip, :contacted, :appointment_date, :notes, :connected, :bad_number, :advisor, :location, :first_appointment_set, :first_appointment_actual, :first_appointment_format, :second_appointment_set, :second_appointment_actual, :second_appointment_format, :enrolled_date, :deposit_date, :sales, :collected, :status, :next_step, :rep_notes, :exclude_from_calling, :meeting_type, :meeting_format, outreaches_attributes: [:id, :outreach_text, :lead_id])
  end
end


    

  

app/helpers/leads_helper.rb
module LeadsHelper

end

app/views/leads/_lead_form.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <%= form_for @lead do |f| %>
        <div class="card-header d-flex align-items-center">
          <h2 class="h5 display">Personal Info</h2>
        </div>
        <div class="update-lead-form">
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control form-control-warning" %>
          </div>
          <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control form-control-warning" %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control form-control-warning" %>
          </div>
          <div class="form-group">
            <%= f.label :phone %>
            <%= f.text_field :phone, class: "form-control form-control-warning" %>
          </div>
          <div class="form-group">
            <%= f.label :city %>
            <%= f.text_field :city, class: "form-control form-control-warning" %>
          </div>
          <div class="form-group">
            <%= f.label :state %>
            <%= f.text_field :state, class: "form-control form-control-warning" %>
          </div>
          <div class="form-group">
            <%= f.label :zip %>
            <%= f.text_field :zip, class: "form-control form-control-warning" %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header d-flex align-items-center">
          <h2 class="h5 display">Setting Up Their Appointment</h2>
        </div>
        <div class="update-lead-form">
          <div class="form-group">
            <%= f.label :location, "Which location do they want to join?", {class: "form-control-label" } %>
            <%= f.select(:location, options_for_select([['Chicago'], ['Online East'], ['Online West']], @lead.location), {:include_blank => 'Select Location'}, {class: 'form-control'}) %>
          </div>
          <div class="form-group">
            <%= f.label :advisor, "Advisor", {class: "form-control-label"} %>
            <%= f.select(:advisor, options_for_select([['Nick']], @lead.advisor), {:include_blank => 'Select Advisor'}, {class: 'form-control'}) %>
          </div>
          <div class="form-group">
            <%= f.label :meeting_type, "Meeting Type", {class: "form-control-label"} %>
            <%= f.select(:meeting_type, options_for_select([['Application Interview'], ['Other']], @lead.meeting_type), {:include_blank => 'Select Meeting Type'}, {class: 'form-control'}) %>
          </div>
          <div class="form-group">
            <%= f.label :meeting_format, "Meeting Format", {class: "form-control-label"} %>
            <%= f.select(:meeting_format, options_for_select([['In-Person'], ['Video Chat'], ['Phone Chat']], @lead.meeting_format), {:include_blank => 'Select Meeting Format'}, {class: 'form-control'}) %>
          </div>
          <div class="form-group">
            <%= f.label :appointment_date, "Appointment Date", {class: "form-control-label"} %>
            <%= f.datetime_field :appointment_date, {class: 'form-control'} %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Begin List of all outreaches -->
  
  <!-- End List fo all outreaches -->

  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header d-flex align-items-center">
          <h2 class="h5 display">Post-Call Records</h2>
        </div>
        <div class="update-lead-form">
        <p> Outreaches:</p>
        <div class="form-group">
          <ul class="outreaches-ul">
            <% @lead_outreaches.each do |outreach| %>
            <li><%= outreach.outreach_text %></li>
          <% end %>
          </ul>
        </div>
        <div class="form-group">
            <div class="i-checks">
              <%= f.label "Latest Outreach" %>
              <%= f.fields_for :outreaches, @lead.outreaches.build do |text| %>
                  <%= text.text_field :outreach_text, class: 'form-control' %>
              <% end %>
            </div>
        </div>
        <div class="form-group">
              <div class="i-checks">
                <%= f.label :next_step, "Next Step" %>
                <%= f.text_field :next_step, class: 'form-control' %>
              </div>
        </div>
          <div class="form-group">
            <div class="i-checks">
              <%= f.label :connected, "Connected?" %>
              <%= f.check_box :connected %>
            </div>
          </div>
          <div class="form-group">
            <div class="i-checks">
              <%= f.label :bad_number, "Bad Number?" %>
              <%= f.check_box :bad_number %>
            </div>
          </div>
          <div class="form-group">
            <div class="i-checks">
              <%= f.label :exclude_from_calling, "Never call again" %>
              <%= f.check_box :exclude_from_calling %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :notes, "Call Converter Notes" %>
            <%= f.text_area :notes, {class: 'form-control'} %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card">
        <% if @call_mode %>
          <div>
            <%= f.hidden_field :call_mode, value: true %>
          </div>
        <% else %>
          <div>
            <div class="card-header d-flex align-items-center">
              <h2 class="h5 display">Admissions Advisor Records</h2>
            </div>
          </div>
          <div class="update-lead-form">
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :first_appointment_set, "First Appointment Set" %>
                <%= f.date_field :first_appointment_set, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :first_appointment_actual, "First Appointment Actually Took Place On" %>
                <%= f.date_field :first_appointment_actual, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :first_appointment_format, "First Appointment Format" %>
                <%= f.select(:first_appointment_format, options_for_select([['Face To Face'], ['Video'], ['Phone']], @lead.first_appointment_format), {:include_blank => 'Select Format'}, {class: 'form-control'}) %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :second_appointment_set, "Second Appointment Set" %>
                <%= f.date_field :second_appointment_set, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :second_appointment_actual, "Second Appointment Actually Took Place On" %>
                <%= f.date_field :second_appointment_actual, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :second_appointment_format, "Second Appointment Format" %>
                <%= f.select(:second_appointment_format, options_for_select([['Face To Face'], ['Video'], ['Phone']], @lead.first_appointment_format), {:include_blank => 'Select Format'}, {class: 'form-control'}) %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :enrolled_date, "Enrolled Date" %>
                <%= f.date_field :enrolled_date, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :deposit_date, "Deposit Date" %>
                <%= f.date_field :deposit_date, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :sales, "Sales" %>
                <%= f.text_field :sales, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :collected, "Collected" %>
                <%= f.text_field :collected, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :status, "Status" %>
                <%= f.select(:status, options_for_select([['In Progress'], ['Enrolled'], ['Stalled']], @lead.status), {:include_blank => 'Select Format'}, {class: 'form-control'}) %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :next_step, "Next Step" %>
                <%= f.text_field :next_step, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="i-checks">
                <%= f.label :rep_notes, "Admission Advisor Notes" %>
                <%= f.text_area :rep_notes, class: 'form-control' %>
              </div>
            </div>
        <% end %>
    </div>
  </div>
</div>
<div class="container">
<div class="row">
    <div class="col-md-6" id="update-btn-col">
      <%= f.submit :next, {value: @call_mode ? "Process and Move On to Next Lead" : "Update", class: 'btn btn-primary btn-lg update-btn'} %>
    </div>
  </div>
</div>
<% end %>

app/views/leads/edit.html.erb
<section class="forms">
  <div class="container-fluid">
    <header>
      <% if @call_mode %>
        <h1 class="h3 display">Next Lead: <%= @lead.full_name %></h1>
      <% else %>
        <h1 class="h3 display">Edit Lead: <%= @lead.full_name %> </h1>
      <% end %>
    </header>

    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-header d-flex align-items-center">
            <h2 class="h5 display">Dial</h2>
          </div>

          <div id="controls">
            <div id="info" style="display:none">
              <p class="instructions">Twilio Client</p>
              <div id="client-name"></div>
            </div>
            <div id="call-controls">
              <p>We think this lead is from <%#= Geocoder.address(@lead.ip) %></p>
              <input id="phone-number" type="text" value="<%= @lead.phone %>" class="form-control"/>
              <select id="from-number" class="form-control">
                <option value="">Choose where to call from:</option>
                <option value="7734666919">Chicago</option>
                <option value="4152125680">San Francisco</option>
                <option value="9175215891">New York City</option>
              </select>
              <button id="button-call" class="btn btn-primary">Call</button>
              <button id="button-hangup" class="btn btn-danger">Hangup</button>
            </div>

             <div id="log"></div>
            <div class="card-header d-flex align-items-center">
              <h2 class="h5 display">Auto Text</h2>
            </div>
            <div id="call-controls">
        
               <%= button_to "Send Auto Text", text_path, method: :post, params: {phone: @lead.phone, body: "Hi #{@lead.first_name} This is Rena from the Actualize coding bootcamp. Do you have a minute to talk?"}, class: "btn btn-primary" %>
            </div>

            <div id="log"></div>
            <div class="card-header d-flex align-items-center">
              <h2 class="h5 display">Send Text Message</h2>
      
            </div>

            <%= form_tag "/text", {class: "form-horizontal text-form"} do %>
            <div class="form-group row">
              <%= label_tag :phone, "Phone", {class: 'col-sm-2'} %>
              <div class="col-sm-10">
                <%= text_field_tag :phone, @lead.phone, {class: "form-control form-control-warning"} %>
              </div>
            </div>
            <div class="form-group row">
              <%= label_tag :body, "Text Body", {class: 'col-sm-2'} %>
              <div class="col-sm-10">
                <%= text_area_tag :body, nil, {class: "form-control form-control-warning"} %>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-lg-2">
                <%= submit_tag "Text", {class: "form-control btn btn-info"} %>
              </div>
            </div>
            <% end %>

          </div>
          <div class="card-header d-flex align-items-center">
            <h2 class="h5 display">History</h2>
          </div>
          <div class="card-block">
            <p>First Became A Lead At: <%= @lead.created_at.strftime("%A %b %e, %l:%M %p") %></p>
            <p>Number Of Times We Called Them: <%= @lead.number_of_dials %></p>

            <div class="row">
              <table class="table">
                <% @lead.events.each do |event| %>
                  <tr><td><%= event.name %></td><td><%= event.updated_at.strftime("%A %b %e, %l:%M %p") %></td></tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
      <% if @messages %>
        <div class="col-lg-6">
          <div class="card">
            <div class="card-header d-flex align-items-center text-history-header">
              <h2 class="h5 display">Text History</h2>
            </div>
            <div class="text-history">
              <% @messages.reverse.each do |message| %>
                <div class="text-bubble alert <%= message.from == "+17734666919" ? 'alert-info' : 'alert-success' %>" role="alert"><p><%= message.body %></p></div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= render 'lead_form' %>

  </div>
</section>


<script type="text/javascript" src="//media.twiliocdn.com/sdk/js/client/v1.3/twilio.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script type="text/javascript">
  $(function () {
  // log('Requesting Capability Token...');
  $.getJSON('/token')
    .done(function (data) {
      log('Got a token.');
      console.log('Token: ' + data.token);

      // Setup Twilio.Device
      Twilio.Device.setup(data.token);

      Twilio.Device.ready(function (device) {
        log('Twilio.Device Ready!');
        document.getElementById('call-controls').style.display = 'block';
      });

      Twilio.Device.error(function (error) {
        log('Twilio.Device Error: ' + error.message);
      });

      Twilio.Device.connect(function (conn) {
        log('Successfully established call!');
        document.getElementById('button-call').style.display = 'none';
        document.getElementById('button-hangup').style.display = 'inline';
      });

      Twilio.Device.disconnect(function (conn) {
        log('Call ended.');
        document.getElementById('button-call').style.display = 'inline';
        document.getElementById('button-hangup').style.display = 'none';
      });

      Twilio.Device.incoming(function (conn) {
        log('Incoming connection from ' + conn.parameters.From);
        var archEnemyPhoneNumber = '+12099517118';

        if (conn.parameters.From === archEnemyPhoneNumber) {
          conn.reject();
          log('It\'s your nemesis. Rejected call.');
        } else {
          // accept the incoming connection and start two-way audio
          conn.accept();
        }
      });

      setClientNameUI(data.identity);
    })
    .fail(function () {
      log('Could not get a token from server!');
    });

  // Bind button to make call
  document.getElementById('button-call').onclick = function () {
    // get the phone number to connect the call to
    var params = {
      To: document.getElementById('phone-number').value,
      FromNumber: document.getElementById('from-number').value
    };

    console.log('Calling ' + params.To + '...');
    Twilio.Device.connect(params);
  };

  // Bind button to hangup call
  document.getElementById('button-hangup').onclick = function () {
    // log('Hanging up...');
    Twilio.Device.disconnectAll();
  };

});

// Activity log
function log(message) {
  var logDiv = document.getElementById('log');
  logDiv.innerHTML += '<p>&gt;&nbsp;' + message + '</p>';
  logDiv.scrollTop = logDiv.scrollHeight;
}

// Set the client name in the UI
function setClientNameUI(clientName) {
  var div = document.getElementById('client-name');
  div.innerHTML = 'Your client name: <strong>' + clientName +
    '</strong>';
}


</script>

app/views/leads/index.html.erb
 <div id="app">
  <section class="charts">
    <div class="container-fluid">
      <header>
        <h1 class="h3">All Leads</h1>
      </header>
      <div class="row">
        Search here:<input type="text" v-model="searchTerm" list="leads">

      </div>
      <div class="row">
        <div class="table-responsive leads-table">
          <table  class="table table-striped table-condensed table-hover" >
            <thead>
              <tr>
                <th v-on:click="sortColumns('created_at')">Created</th>
                <th v-on:click="sortColumns('first_name')">First Name</th>
                <th v-on:click="sortColumns('last_name')">Last Name</th>
                <th v-on:click="sortColumns('email')">Email</th>
                <th v-on:click="sortColumns('phone')">Phone</th>
                <th v-on:click="sortColumns('appointment_date')">Appointment Date</th>
                <th>Call Converter Notes</th>
              </tr>
            </thead>
            <tbody v-for="lead in leads" v-if="foundLead(lead)" v-bind:style="{'background-color': emptyOutreach(lead.outreaches, lead.events)}">
              
                <tr data-toggle="collapse" :data-target="'#events' + lead.id" class="accordion-toggle">
                  <td>{{ moment(lead.created_at).format('dddd MMM Do YYYY, h:mm a') }}</td>
                  <td>{{ lead.first_name }}</td>
                  <td>{{ lead.last_name }}</td>
                  <td><a href="" v-on:click="edit(lead)" >{{ lead.email }}</a></td>
                  <td>{{ lead.phone }}</td>
                  <td>{{ moment(lead.appointment_date).format('dddd MMM Do YYYY, h:mm a') }}</td>
                  <td>{{ lead.notes }}</td>
                </tr>
                
                  <tr>
                    <td colspan="7" class="hiddenRow">
                      <div class="accordion-body collapse" v-bind:id="'events' + lead.id"> 
                        <table v-for="event in lead.events" class="table">
                          <div>         
                             <tr><td>{{ event.name}}</td>
                             <td>{{ moment(event.updated_at).format('dddd MMM Do YYYY, h:mm a') }}</td> </tr>
              
                        </div>
                      </table>
                      </div>

                    </td>
                </tr>


            </tbody>
          </table>
        </div>
      </div>
  </section>
</div>

app/views/leads/new.html.erb
<div class="card">
  <%= form_for @lead do |f| %>
    <div class="card-header d-flex align-items-center">
      <h2 class="h5 display">Personal Info</h2>
    </div>
    <div class="update-lead-form">
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control form-control-warning" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control form-control-warning" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control form-control-warning" %>
      </div>
      <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: "form-control form-control-warning" %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control form-control-warning" %>
      </div>
      <div class="form-group">
        <%= f.label :state %>
        <%= f.text_field :state, class: "form-control form-control-warning" %>
      </div>
      <div class="form-group">
        <%= f.label :zip %>
        <%= f.text_field :zip, class: "form-control form-control-warning" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6" id="update-btn-col">
        <%= f.submit :save %>
      </div>
    </div>
  <% end %>
</div>

app/views/leads/no_leads.html.erb
<h1>No more leads!</h1>
<%= link_to "Try Again", '/' %>